### ISSUE TITLE
Xtract 2.0.0 is not published for Scala 2.11

### ISSUE THREAD

**Issue by alexflav23** [lucidsoftware/xtract#15]
While there is a release artefact for 2.0.0_2.11 under the Git tag for the 2.0.0 release, it's not actually published to Central.

I've not seen an obvious crossScalaVersion definition in `build.sbt`, so perhaps this is no longer supported?

Getting some problems using 1.3.1 with Scala 2.11.12, and I was hoping an upgrade would fix things.

```scala
Error: could not find implicit value for parameter semigroupal: cats.Functor[com.lucidchart.xtract.XmlReader]

Error: could not find implicit value for parameter functor: cats.Semigroupal[com.lucidchart.xtract.XmlReader]
```
I'm relying on the following top level imports:
```scala
import com.lucidchart.open.xtract.{ XmlReader, __ }
import com.lucidchart.open.xtract.XmlReader._
import cats.syntax.all._
```

**Comment by tmccombs** [comment]
hmm, that's odd, I'll look into it.

**Comment by tmccombs** [comment]
I rebuilt it for 2.11 and tried publishing to sonatype. Hopefully it should show up soon.

**Comment by tmccombs** [comment]
I apparently don't know how to use sonatype. I thought I went through the flow to release the 2.0.0 version, but that repository seems to have just disappeared.

**Comment by alexflav23** [comment]
@tmccombs I think you just need to go through the sonatype saga of promoting to Central? Not sure how you usually publish tbh.

**Comment by tmccombs** [comment]
well, I couldn't figure out how to publish as 2.0.0, but I was able to publish as 2.0.1
