### ISSUE TITLE
Default XmlReader[Long]

### ISSUE THREAD

**Issue by jazott3** [lucidsoftware/xtract#20]
Hello! I work on several projects that use xtract, and noticed it does not ship with a default XmlReader[Long]. I have been thinking about adding one for a few months, and I am wondering if that would be a welcome feature/contribution or not.

Thanks
Joe

**Comment by tmccombs** [comment]
Yes! If you make a pull request for that I would be happy to merge it.

**Comment by jazott3** [comment]
Great! PR is up.

**Comment by Ssstlis** [comment]
Should we publish updated version?
Because i need to package it manually.

**Comment by tmccombs** [comment]
@Ssstlis yes. I have just published version 2.1.0 which should include this change.
